name: Build and Deploy
run-name: Build and Upload Image
on: [push]
jobs:
  container-build:
    runs-on: christianbingman-com-runners
    container: nixos/nix:latest
    steps:
      - name: Checkout
        run: |
          git clone -n --depth 1 $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
          git fetch origin $GITHUB_REF
          git reset --hard $GITHUB_SHA
      - name: Build container
        run: nix build .#docker --extra-experimental-features nix-command --extra-experimental-features flakes
      - name: Upload container
        uses: actions/upload-artifact@v4
        with:
          name: container.tar
          path: ./result

