name: Build and Deploy
run-name: Build and Upload Image
on: [push]
jobs:
  container-build:
    runs-on: christianbingman-com-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix Deps
        run: sudo apt install xz-utils
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build container
        run: nix build .#docker
      - name: Upload container
        uses: actions/upload-artifact@v4
        with:
          name: container.tar
          path: ./result
  container-push:
    runs-on: christianbingman-com-runners
    needs: container-build
    steps:
      - name: Download container tar
        uses: actions/download-artifact@v4
        with:
          name: container.tar
      - name: Load container image
        run: docker load < result
      - name: Push image to repo
        run: "docker push registry.christianbingman.com/personal-site:latest"
