name: Build and Deploy
run-name: Build and Upload Image
on: [push]
jobs:
  container-build:
    runs-on: christianbingman-com-runners
    container: nixos/nix:latest
    steps:
      - name: Set up checkout dependancies
        run: nix-env -iA nixpkgs.nodejs
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build container
        run: nix build .#docker --extra-experimental-features nix-command --extra-experimental-features flakes
      - name: Upload container
        uses: actions/upload-artifact@v4
        with:
          name: container.tar
          path: ./result

